# Generated by Django 3.2.7 on 2021-10-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211001_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlogs',
            name='employee',
        ),
    ]
